import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { siteTitle } from '../components/layout'

let sections = [
  {
    href: `/map`,
    text: `View the map`
  },
  {
    href: `/projects`,
    text: `View a list of projects`
  },
  {
    href: `/reporter`,
    text: `Report a project`
  },
  {
    href: `/meetings`,
    text: `View upcoming meetings`
  }
]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {siteTitle}
        </h1>
        {sections.map(sec => (
          <div>
            <Link href={sec.href}>

            <a>{sec.text}</a>
            </Link>
          </div>
        ))}
      </main>

      <footer className={styles.footer}>
        it is 2021
      </footer>
    </div>
  )
}
